# Lumetra — Analista Financeiro Inteligente


## 1. Importação das bibliotecas

In [1]:
import pandas as pd

## 2. Extração dos dados
    leitura de vendas_brutas_ia_python.csv

In [2]:
df = pd.read_csv('Dados/Brutos/vendas_brutas_ia_python.csv')
display(df.head(20))

,id_pedido,data_hora,loja,id_cliente,categoria,produto,quantidade,preco_unitario,desconto,custo_unitario,faturamento,forma_pagamento,status
0,PED00964,2025-09-01 02:45:00,Taguatinga,CLI1729,Eletrônicos,Smartwatch,2,219.9,0.15,130.0,373.83,PIX,Concluído
1,PED08693,2025-09-01 03:23:00,Taguatinga,CLI0203,Informática,Webcam,4,159.9,0.00,88.0,639.60,PIX,Concluído
2,PED02240,2025-09-01 03:39:00,Taguatinga,CLI1118,Informática,Teclado,3,119.9,0.05,55.0,341.72,Cartão de Crédito,Concluído
3,PED09734,2025-09-01 05:00:00,Asa Sul,CLI1717,Eletrônicos,Caixa de Som,1,149.9,0.05,82.0,142.41,PIX,Concluído
4,PED09063,2025-09-01 06:20:00,Águas Claras,CLI0478,Acessórios,Suporte Notebook,1,79.9,0.00,36.0,79.90,PIX,Concluído
5,PED04062,2025-09-01 08:22:00,Taguatinga,CLI1001,Eletrônicos,Fone Bluetooth,1,89.9,0.00,48.0,89.90,PIX,Concluído
6,PED01080,2025-09-01 09:12:00,Ceilândia,CLI0752,Informática,Teclado,1,119.9,0.05,55.0,113.91,PIX,Concluído
7,PED06070,2025-09-01 09:33:00,Asa Sul,CLI1909,Informática,Webcam,4,159.9,0.10,88.0,575.64,Cartão de Crédito,Concluído
8,PED04018,2025-09-01 11:17:00,Asa Sul,CLI0250,Eletrônicos,Smartwatch,1,219.9,0.00,130.0,219.90,Cartão de Débito,Concluído
9,PED05475,2025-09-01 11:47:00,Asa Sul,CLI1072,Eletrônicos,Fone Bluetooth,4,89.9,0.15,48.0,305.66,Cartão de Débito,Concluído
10,PED08677,2025-09-01 11:47:00,Ceilândia,CLI1474,Informática,Teclado,2,119.9,0.00,55.0,239.80,Cartão de Crédito,Concluído
11,PED09430,2025-09-01 15:06:00,Ceilândia,CLI0340,Acessórios,Suporte Notebook,1,79.9,0.05,36.0,75.91,Cartão de Débito,Concluído
12,PED07168,2025-09-01 16:25:00,Guará,CLI2103,Informática,Mouse,1,69.9,0.00,31.0,69.90,Cartão de Débito,Concluído
13,PED00887,2025-09-01 16:33:00,Ceilândia,CLI1029,Eletrônicos,Fone Bluetooth,3,89.9,0.00,48.0,269.70,PIX,Concluído
14,PED06030,2025-09-01 19:47:00,Águas Claras,CLI0442,Eletrônicos,Caixa de Som,4,149.9,0.00,82.0,599.60,PIX,Devolvido
15,PED06598,2025-09-01 21:05:00,Guará,CLI1424,Acessórios,Carregador,4,59.9,0.00,25.0,239.60,PIX,Concluído
16,PED02806,2025-09-01 21:07:00,Guará,CLI2162,Informática,Webcam,1,159.9,0.00,88.0,159.90,Dinheiro,Concluído
17,PED02215,2025-09-01 21:08:00,Águas Claras,CLI1156,Eletrônicos,Smartwatch,1,219.9,0.00,130.0,219.90,Dinheiro,Cancelado
18,PED07918,2025-09-01 21:22:00,Ceilândia,CLI1701,Eletrônicos,Fone Bluetooth,4,89.9,0.00,48.0,359.60,PIX,Concluído
19,PED05272,2025-09-01 22:35:00,Guará,CLI2153,Acessórios,Cabo USB-C,1,29.9,0.00,11.0,29.90,Cartão de Crédito,Concluído

## 3. Diagnóstico dos dados
    info()
    valores nulos
    duplicados
    inconsistências...

In [3]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 10030 entries, 0 to 10029
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_pedido        10030 non-null  str
 1   data_hora        10030 non-null  str
 2   loja             10030 non-null  str
 3   id_cliente       10005 non-null  str
 4   categoria        10030 non-null  str
 5   produto          10030 non-null  str
 6   quantidade       10030 non-null  int64
 7   preco_unitario   10030 non-null  float64
 8   desconto         10005 non-null  float64
 9   custo_unitario   10030 non-null  float64
 10  faturamento      10030 non-null  float64
 11  forma_pagamento  10005 non-null  str
 12  status           10030 non-null  str
dtypes: float64(4), int64(1), str(8)
memory usage: 1018.8 KB
None

In [4]:
df.isnull().sum()

id_pedido           0
data_hora           0
loja                0
id_cliente         25
categoria           0
produto             0
quantidade          0
preco_unitario      0
desconto           25
custo_unitario      0
faturamento         0
forma_pagamento    25
status              0
dtype: int64

A base possui 10.030 registros e 13 colunas. Foram identificados 25 valores ausentes nas colunas id_cliente, desconto e forma_pagamento. Além disso, data_hora foi importada como texto (str) e deverá ser convertida para datetime para possibilitar análises temporais. Os identificadores id_pedido e id_cliente podem permanecer como texto, pois representam códigos e não grandezas numéricas.

In [5]:
df.duplicated().sum()

np.int64(30)

Foram identificados 30 registros duplicados na base de dados. Esses registros deverão ser analisados e, caso sejam duplicações indevidas, removidos durante a etapa de tratamento para evitar distorções nos indicadores e análises

In [6]:
df[df.duplicated(keep=False)].sort_values("id_pedido")

,id_pedido,data_hora,loja,id_cliente,categoria,produto,quantidade,preco_unitario,desconto,custo_unitario,faturamento,forma_pagamento,status
6340,PED00048,2026-04-18 18:33:00,Ceilândia,CLI2093,Informática,Webcam,2,159.9,0.10,88.0,287.82,Dinheiro,Concluído
10005,PED00048,2026-04-18 18:33:00,Ceilândia,CLI2093,Informática,Webcam,2,159.9,0.10,88.0,287.82,Dinheiro,Concluído
10012,PED00957,2026-03-11 20:18:00,Águas Claras,CLI1958,Acessórios,Cabo USB-C,2,29.9,0.10,11.0,53.82,PIX,Concluído
5272,PED00957,2026-03-11 20:18:00,Águas Claras,CLI1958,Acessórios,Cabo USB-C,2,29.9,0.10,11.0,53.82,PIX,Concluído
8847,PED01059,2026-07-20 10:28:00,Guará,CLI0309,Acessórios,Cabo USB-C,2,29.9,0.05,11.0,56.81,PIX,Concluído
10029,PED01059,2026-07-20 10:28:00,Guará,CLI0309,Acessórios,Cabo USB-C,2,29.9,0.05,11.0,56.81,PIX,Concluído
10007,PED01066,2026-03-09 08:48:00,Asa Sul,CLI0210,Acessórios,Cabo USB-C,1,29.9,0.10,11.0,26.91,Dinheiro,Concluído
5202,PED01066,2026-03-09 08:48:00,Asa Sul,CLI0210,Acessórios,Cabo USB-C,1,29.9,0.10,11.0,26.91,Dinheiro,Concluído
10008,PED01241,2026-04-19 21:05:00,Guará,CLI0756,Acessórios,Carregador,1,59.9,0.05,25.0,56.90,Cartão de Débito,Concluído
6363,PED01241,2026-04-19 21:05:00,Guará,CLI0756,Acessórios,Carregador,1,59.9,0.05,25.0,56.90,Cartão de Débito,Concluído
4684,PED01690,2026-02-16 17:31:00,Águas Claras,CLI1396,Eletrônicos,Fone Bluetooth,4,89.9,0.15,48.0,305.66,Cartão de Débito,Cancelado
10001,PED01690,2026-02-16 17:31:00,Águas Claras,CLI1396,Eletrônicos,Fone Bluetooth,4,89.9,0.15,48.0,305.66,Cartão de Débito,Cancelado
4521,PED01717,2026-02-10 20:13:00,Taguatinga,CLI0613,Acessórios,Suporte Notebook,3,79.9,0.10,36.0,215.73,Dinheiro,Concluído
10004,PED01717,2026-02-10 20:13:00,Taguatinga,CLI0613,Acessórios,Suporte Notebook,3,79.9,0.10,36.0,215.73,Dinheiro,Concluído
576,PED02401,2025-09-19 20:39:00,Águas Claras,CLI1061,Eletrônicos,Fone Bluetooth,3,89.9,0.10,48.0,242.73,PIX,Concluído
10006,PED02401,2025-09-19 20:39:00,Águas Claras,CLI1061,Eletrônicos,Fone Bluetooth,3,89.9,0.10,48.0,242.73,PIX,Concluído
10027,PED02547,2026-06-27 00:57:00,Guará,CLI2466,Informática,Teclado,3,119.9,0.00,55.0,359.70,PIX,Concluído
8243,PED02547,2026-06-27 00:57:00,Guará,CLI2466,Informática,Teclado,3,119.9,0.00,55.0,359.70,PIX,Concluído
10003,PED02896,2026-02-19 01:18:00,Águas Claras,CLI1881,Acessórios,Carregador,2,59.9,0.00,25.0,119.80,Cartão de Débito,Concluído
4742,PED02896,2026-02-19 01:18:00,Águas Claras,CLI1881,Acessórios,Carregador,2,59.9,0.00,25.0,119.80,Cartão de Débito,Concluído
9920,PED02946,2026-08-28 23:54:00,Ceilândia,CLI1507,Eletrônicos,Fone Bluetooth,1,89.9,0.05,48.0,85.41,PIX,Concluído
10025,PED02946,2026-08-28 23:54:00,Ceilândia,CLI1507,Eletrônicos,Fone Bluetooth,1,89.9,0.05,48.0,85.41,PIX,Concluído
7487,PED03080,2026-05-30 03:30:00,Guará,CLI1481,Acessórios,Carregador,4,59.9,0.05,25.0,227.62,Cartão de Crédito,Concluído
10011,PED03080,2026-05-30 03:30:00,Guará,CLI1481,Acessórios,Carregador,4,59.9,0.05,25.0,227.62,Cartão de Crédito,Concluído
5653,PED03173,2026-03-26 03:30:00,Ceilândia,CLI0425,Acessórios,Cabo USB-C,1,29.9,0.00,11.0,29.90,Dinheiro,Concluído
10013,PED03173,2026-03-26 03:30:00,Ceilândia,CLI0425,Acessórios,Cabo USB-C,1,29.9,0.00,11.0,29.90,Dinheiro,Concluído
10014,PED03479,2026-01-22 16:38:00,Ceilândia,CLI0083,Acessórios,Cabo USB-C,1,29.9,0.00,11.0,29.90,Cartão de Crédito,Concluído
3999,PED03479,2026-01-22 16:38:00,Ceilândia,CLI0083,Acessórios,Cabo USB-C,1,29.9,0.00,11.0,29.90,Cartão de Crédito,Concluído
1731,PED03852,2025-11-01 16:45:00,Ceilândia,CLI0436,Eletrônicos,Fone Bluetooth,1,89.9,0.00,48.0,89.90,PIX,Concluído
10002,PED03852,2025-11-01 16:45:00,Ceilândia,CLI0436,Eletrônicos,Fone Bluetooth,1,89.9,0.00,48.0,89.90,PIX,Concluído
7051,PED03861,2026-05-14 18:42:00,Águas Claras,CLI1777,Acessórios,Carregador,1,59.9,0.15,25.0,50.91,Cartão de Débito,Concluído
10018,PED03861,2026-05-14 18:42:00,Águas Claras,CLI1777,Acessórios,Carregador,1,59.9,0.15,25.0,50.91,Cartão de Débito,Concluído
8158,PED04061,2026-06-23 21:04:00,Águas Claras,CLI2191,Eletrônicos,Smartwatch,2,219.9,0.05,130.0,417.81,Cartão de Débito,Concluído
10019,PED04061,2026-06-23 21:04:00,Águas Claras,CLI2191,Eletrônicos,Smartwatch,2,219.9,0.05,130.0,417.81,Cartão de Débito,Concluído
10010,PED04176,2025-12-09 02:54:00,Águas Claras,CLI2441,Acessórios,Cabo USB-C,3,29.9,0.10,11.0,80.73,Dinheiro,Concluído
2750,PED04176,2025-12-09 02:54:00,Águas Claras,CLI2441,Acessórios,Cabo USB-C,3,29.9,0.10,11.0,80.73,Dinheiro,Concluído
10017,PED04854,2026-08-29 07:37:00,Asa Sul,CLI1704,Eletrônicos,Fone Bluetooth,4,89.9,0.00,48.0,359.60,Dinheiro,Concluído
9930,PED04854,2026-08-29 07:37:00,Asa Sul,CLI1704,Eletrônicos,Fone Bluetooth,4,89.9,0.00,48.0,359.60,Dinheiro,Concluído
10028,PED05155,2026-04-28 03:46:00,Asa Sul,CLI0368,Informática,Teclado,4,119.9,0.10,55.0,431.64,Dinheiro,Concluído
6590,PED05155,2026-04-28 03:46:00,Asa Sul,CLI0368,Informática,Teclado,4,119.9,0.10,55.0,431.64,Dinheiro,Concluído
10015,PED05175,2026-04-08 02:46:00,Ceilândia,CLI0476,Eletrônicos,Smartwatch,3,219.9,0.00,130.0,659.70,PIX,Concluído
6033,PED05175,2026-04-08 02:46:00,Ceilândia,CLI0476,Eletrônicos,Smartwatch,3,219.9,0.00,130.0,659.70,PIX,Concluído
582,PED05542,2025-09-20 01:24:00,Ceilândia,CLI1582,Eletrônicos,Smartwatch,4,219.9,0.00,130.0,879.60,Dinheiro,Cancelado
10016,PED05542,2025-09-20 01:24:00,Ceilândia,CLI1582,Eletrônicos,Smartwatch,4,219.9,0.00,130.0,879.60,Dinheiro,Cancelado
439,PED06003,2025-09-15 01:14:00,Águas Claras,CLI2257,Acessórios,Suporte Notebook,4,79.9,0.10,36.0,287.64,Dinheiro,Cancelado
10009,PED06003,2025-09-15 01:14:00,Águas Claras,CLI2257,Acessórios,Suporte Notebook,4,79.9,0.10,36.0,287.64,Dinheiro,Cancelado
9485,PED06005,2026-08-13 22:34:00,Guará,CLI0037,Acessórios,Carregador,1,59.9,0.05,25.0,56.90,Cartão de Débito,Concluído
10023,PED06005,2026-08-13 22:34:00,Guará,CLI0037,Acessórios,Carregador,1,59.9,0.05,25.0,56.90,Cartão de Débito,Concluído
4947,PED06076,2026-02-27 14:41:00,Águas Claras,CLI1585,Eletrônicos,Fone Bluetooth,1,89.9,0.00,48.0,89.90,Cartão de Crédito,Concluído
10024,PED06076,2026-02-27 14:41:00,Águas Claras,CLI1585,Eletrônicos,Fone Bluetooth,1,89.9,0.00,48.0,89.90,Cartão de Crédito,Concluído
9896,PED06160,2026-08-28 00:13:00,Águas Claras,CLI0160,Eletrônicos,Caixa de Som,3,149.9,0.00,82.0,449.70,Cartão de Débito,Concluído
10020,PED06160,2026-08-28 00:13:00,Águas Claras,CLI0160,Eletrônicos,Caixa de Som,3,149.9,0.00,82.0,449.70,Cartão de Débito,Concluído
2249,PED07214,2025-11-21 03:54:00,Asa Sul,CLI2051,Eletrônicos,Smartwatch,2,219.9,0.05,130.0,417.81,Dinheiro,Concluído
10021,PED07214,2025-11-21 03:54:00,Asa Sul,CLI2051,Eletrônicos,Smartwatch,2,219.9,0.05,130.0,417.81,Dinheiro,Concluído
1963,PED08149,2025-11-10 23:11:00,Águas Claras,CLI1750,Eletrônicos,Fone Bluetooth,4,89.9,0.15,48.0,305.66,Cartão de Débito,Cancelado
10026,PED08149,2025-11-10 23:11:00,Águas Claras,CLI1750,Eletrônicos,Fone Bluetooth,4,89.9,0.15,48.0,305.66,Cartão de Débito,Cancelado
10022,PED09300,2026-02-15 01:19:00,Ceilândia,CLI0118,Acessórios,Carregador,1,59.9,0.10,25.0,53.91,Cartão de Débito,Concluído
4640,PED09300,2026-02-15 01:19:00,Ceilândia,CLI0118,Acessórios,Carregador,1,59.9,0.10,25.0,53.91,Cartão de Débito,Concluído
10000,PED09809,2026-04-15 19:02:00,Taguatinga,CLI2477,Eletrônicos,Smartwatch,4,219.9,0.05,130.0,835.62,Dinheiro,Concluído
6252,PED09809,2026-04-15 19:02:00,Taguatinga,CLI2477,Eletrônicos,Smartwatch,4,219.9,0.05,130.0,835.62,Dinheiro,Concluído

Foram identificados 30 registros duplicados na base. Os registros apresentam pedidos repetidos, indicando uma possível inconsistência na origem dos dados, como duplicidade de lançamento ou falha no processo de registro. Em um cenário real, a causa deveria ser investigada antes da remoção, a fim de confirmar se são duplicações indevidas ou transações legítimas.

In [7]:
df['loja'].value_counts()

loja
Guará           2045
Ceilândia       1997
Asa Sul         1986
Taguatinga      1984
Águas Claras    1983
aguas claras      12
TAGUATINGA        12
Asa sul           11
Name: count, dtype: int64

Foram identificadas inconsistências de padronização na coluna loja. Algumas unidades aparecem representadas de diferentes formas, como Águas Claras e aguas claras, Taguatinga e TAGUATINGA, além de Asa Sul e Asa sul. Embora representem aparentemente as mesmas unidades, essas variações fazem com que sejam interpretadas como categorias distintas, podendo distorcer análises e indicadores por loja. Os valores deverão ser padronizados durante o tratamento dos dados.

In [8]:
display(df.describe())

         quantidade  preco_unitario     desconto  custo_unitario   faturamento
count  10030.000000    10030.000000  10005.00000    10030.000000  10030.000000
mean       1.875174      108.957926      0.05004       56.426221    195.423143
std        1.052975       56.371245      0.05776       35.563740    160.446463
min        0.000000     -219.900000      0.00000       11.000000     25.410000
25%        1.000000       69.900000      0.00000       31.000000     79.900000
50%        2.000000       89.900000      0.00000       48.000000    143.910000
75%        2.000000      149.900000      0.10000       82.000000    242.730000
max        4.000000      219.900000      0.15000      130.000000    879.600000

A análise estatística das variáveis numéricas revelou possíveis inconsistências. A coluna quantidade apresenta valor mínimo igual a 0, enquanto preco_unitario apresenta valor mínimo negativo de -219,90. Esses registros precisam ser investigados, pois podem representar erros de preenchimento ou processamento dos dados. Também foi observado faturamento médio de aproximadamente 195,42 e desconto médio de 5%.

In [9]:
df[df['quantidade'] <= 0]

,id_pedido,data_hora,loja,id_cliente,categoria,produto,quantidade,preco_unitario,desconto,custo_unitario,faturamento,forma_pagamento,status
621,PED03674,2025-09-21 09:49:00,Asa Sul,CLI1670,Eletrônicos,Fone Bluetooth,0,89.9,0.15,48.0,76.42,Dinheiro,Concluído
2864,PED04159,2025-12-13 19:32:00,Ceilândia,CLI2449,Eletrônicos,Smartwatch,0,219.9,0.00,130.0,879.60,Dinheiro,Concluído
3820,PED04313,2026-01-16 17:09:00,Asa Sul,CLI0490,Acessórios,Cabo USB-C,0,29.9,0.00,11.0,59.80,Cartão de Débito,Concluído
3874,PED09392,2026-01-18 17:15:00,Asa Sul,CLI1541,Informática,Mouse,0,69.9,0.00,31.0,209.70,Cartão de Débito,Concluído
7710,PED00639,2026-06-06 19:42:00,Águas Claras,CLI2294,Informática,Teclado,0,119.9,0.00,55.0,239.80,Dinheiro,Concluído

In [10]:
df[df['preco_unitario'] <= 0]

,id_pedido,data_hora,loja,id_cliente,categoria,produto,quantidade,preco_unitario,desconto,custo_unitario,faturamento,forma_pagamento,status
1050,PED08547,2025-10-08 07:39:00,Ceilândia,CLI0815,Informática,Mouse,1,-69.9,0.00,31.0,69.90,Cartão de Débito,Concluído
1868,PED09210,2025-11-06 16:55:00,Taguatinga,CLI2400,Informática,Mouse,1,-69.9,0.05,31.0,66.41,Cartão de Débito,Concluído
4046,PED07733,2026-01-24 09:04:00,Guará,CLI0736,Eletrônicos,Caixa de Som,1,-149.9,0.15,82.0,127.42,Dinheiro,Cancelado
4577,PED05366,2026-02-12 20:45:00,Asa Sul,CLI0968,Eletrônicos,Smartwatch,1,-219.9,0.00,130.0,219.90,Dinheiro,Concluído
9400,PED00589,2026-08-10 19:50:00,Taguatinga,CLI1273,Informática,Teclado,4,-119.9,0.00,55.0,479.60,PIX,Concluído

Foram identificados 5 registros com preco_unitario negativo. Ao comparar esses registros com o faturamento, observa-se que os valores negativos parecem representar inconsistências no sinal do preço, enquanto o faturamento foi calculado considerando valores positivos. Em um cenário real, seria necessário validar a regra de negócio e a origem dos registros antes da correção.

In [11]:
df["status"].value_counts()

status
Concluído    9420
Cancelado     415
Devolvido     195
Name: count, dtype: int64

In [12]:
df["forma_pagamento"].value_counts(dropna=False)

forma_pagamento
Cartão de Débito     2582
PIX                  2514
Dinheiro             2460
Cartão de Crédito    2449
NaN                    25
Name: count, dtype: int64

In [13]:
df[df["forma_pagamento"].isnull()]["status"].value_counts()

status
Concluído    22
Cancelado     3
Name: count, dtype: int64

Dos 25 registros com forma_pagamento ausente, 22 correspondem a pedidos concluídos e 3 a pedidos cancelados. Portanto, a ausência desse dado não está restrita a cancelamentos e pode representar uma falha no registro da forma de pagamento. A origem da inconsistência deveria ser investigada antes da definição do tratamento.

In [14]:
df[df["desconto"].isnull()][
    ["id_pedido", "produto", "quantidade", "preco_unitario", "desconto", "faturamento", "status"]
]

,id_pedido,produto,quantidade,preco_unitario,desconto,faturamento,status
478,PED02316,Fone Bluetooth,2,89.9,NaN,179.80,Concluído
500,PED06190,Carregador,1,59.9,NaN,59.90,Concluído
752,PED05686,Cabo USB-C,1,29.9,NaN,28.40,Concluído
889,PED08744,Smartwatch,4,219.9,NaN,879.60,Concluído
2920,PED07443,Suporte Notebook,1,79.9,NaN,67.92,Concluído
3360,PED05466,Carregador,1,59.9,NaN,59.90,Concluído
3730,PED01898,Teclado,1,119.9,NaN,107.91,Concluído
4048,PED05962,Suporte Notebook,1,79.9,NaN,71.91,Concluído
4096,PED05230,Caixa de Som,2,149.9,NaN,269.82,Concluído
4583,PED06865,Webcam,1,159.9,NaN,159.90,Concluído
5314,PED03127,Teclado,3,119.9,NaN,341.72,Concluído
5830,PED01294,Fone Bluetooth,4,89.9,NaN,341.62,Concluído
6072,PED07757,Smartwatch,2,219.9,NaN,373.83,Concluído
6160,PED01183,Mouse,1,69.9,NaN,59.42,Concluído
6211,PED03566,Caixa de Som,2,149.9,NaN,284.81,Concluído
6662,PED09260,Caixa de Som,4,149.9,NaN,569.62,Concluído
6966,PED09235,Carregador,1,59.9,NaN,50.91,Concluído
7478,PED01321,Smartwatch,1,219.9,NaN,208.91,Concluído
8129,PED05629,Cabo USB-C,1,29.9,NaN,28.40,Concluído
8260,PED09744,Caixa de Som,3,149.9,NaN,449.70,Concluído
8420,PED06972,Mouse,1,69.9,NaN,66.41,Concluído
8462,PED07319,Carregador,1,59.9,NaN,53.91,Concluído
8817,PED07620,Teclado,1,119.9,NaN,119.90,Concluído
9733,PED02363,Webcam,2,159.9,NaN,319.80,Concluído
9897,PED03304,Caixa de Som,2,149.9,NaN,254.83,Concluído

Foram identificados 25 registros com desconto ausente. Não foi possível determinar a causa da ausência, não podemos simplesmente substituir todos os NaN de desconto por 0, porque perderíamos informação.. Para preservar esses registros, podemos reconstruir o desconto usando as outras informações da própria venda.

In [15]:
descontos_nulos = df[df["desconto"].isnull()].copy()

descontos_nulos["desconto_calculado"] = (
    (descontos_nulos["quantidade"] * descontos_nulos["preco_unitario"])
    - descontos_nulos["faturamento"]
) / (
    descontos_nulos["quantidade"] * descontos_nulos["preco_unitario"]
)

descontos_nulos[
    ["produto", "quantidade", "preco_unitario",
     "faturamento", "desconto_calculado"]
]

descontos_nulos["desconto_percentual"] = (
    descontos_nulos["desconto_calculado"] * 100
).round(0)

descontos_nulos[
    ["produto", "quantidade", "preco_unitario",
     "faturamento", "desconto_percentual"]
]

,produto,quantidade,preco_unitario,faturamento,desconto_percentual
478,Fone Bluetooth,2,89.9,179.80,0.0
500,Carregador,1,59.9,59.90,0.0
752,Cabo USB-C,1,29.9,28.40,5.0
889,Smartwatch,4,219.9,879.60,0.0
2920,Suporte Notebook,1,79.9,67.92,15.0
3360,Carregador,1,59.9,59.90,0.0
3730,Teclado,1,119.9,107.91,10.0
4048,Suporte Notebook,1,79.9,71.91,10.0
4096,Caixa de Som,2,149.9,269.82,10.0
4583,Webcam,1,159.9,159.90,0.0
5314,Teclado,3,119.9,341.72,5.0
5830,Fone Bluetooth,4,89.9,341.62,5.0
6072,Smartwatch,2,219.9,373.83,15.0
6160,Mouse,1,69.9,59.42,15.0
6211,Caixa de Som,2,149.9,284.81,5.0
6662,Caixa de Som,4,149.9,569.62,5.0
6966,Carregador,1,59.9,50.91,15.0
7478,Smartwatch,1,219.9,208.91,5.0
8129,Cabo USB-C,1,29.9,28.40,5.0
8260,Caixa de Som,3,149.9,449.70,0.0
8420,Mouse,1,69.9,66.41,5.0
8462,Carregador,1,59.9,53.91,10.0
8817,Teclado,1,119.9,119.90,0.0
9733,Webcam,2,159.9,319.80,0.0
9897,Caixa de Som,2,149.9,254.83,15.0

In [16]:
df[df["id_cliente"].isnull()]

,id_pedido,data_hora,loja,id_cliente,categoria,produto,quantidade,preco_unitario,desconto,custo_unitario,faturamento,forma_pagamento,status
32,PED00312,2025-09-02 08:38:00,Taguatinga,NaN,Informática,Mouse,2,69.9,0.00,31.0,139.80,Cartão de Débito,Concluído
399,PED07780,2025-09-14 03:53:00,Taguatinga,NaN,Eletrônicos,Caixa de Som,1,149.9,0.05,82.0,142.41,Dinheiro,Concluído
546,PED00352,2025-09-18 16:48:00,Guará,NaN,Eletrônicos,Fone Bluetooth,2,89.9,0.00,48.0,179.80,PIX,Devolvido
1014,PED02312,2025-10-06 09:59:00,Águas Claras,NaN,Eletrônicos,Fone Bluetooth,4,89.9,0.10,48.0,323.64,Dinheiro,Concluído
1477,PED00933,2025-10-23 08:19:00,Taguatinga,NaN,Eletrônicos,Caixa de Som,3,149.9,0.00,82.0,449.70,Cartão de Débito,Concluído
1950,PED08307,2025-11-10 08:09:00,Guará,NaN,Acessórios,Carregador,1,59.9,0.00,25.0,59.90,PIX,Concluído
2559,PED08626,2025-12-02 17:16:00,Taguatinga,NaN,Eletrônicos,Caixa de Som,4,149.9,0.05,82.0,569.62,NaN,Concluído
2589,PED03224,2025-12-03 15:57:00,Taguatinga,NaN,Informática,Mouse,3,69.9,0.00,31.0,209.70,Dinheiro,Concluído
2656,PED04963,2025-12-05 23:19:00,Taguatinga,NaN,Informática,Webcam,1,159.9,0.15,88.0,135.91,Cartão de Débito,Concluído
4188,PED02847,2026-01-29 20:49:00,Asa Sul,NaN,Informática,Teclado,1,119.9,0.00,55.0,119.90,Cartão de Débito,Concluído
4205,PED01412,2026-01-30 07:26:00,Águas Claras,NaN,Acessórios,Suporte Notebook,1,79.9,0.00,36.0,79.90,Cartão de Débito,Concluído
4495,PED00452,2026-02-09 10:23:00,Taguatinga,NaN,Informática,Webcam,1,159.9,0.05,88.0,151.91,Cartão de Crédito,Concluído
4960,PED09068,2026-02-28 05:47:00,Águas Claras,NaN,Acessórios,Carregador,2,59.9,0.00,25.0,119.80,Dinheiro,Cancelado
4974,PED08829,2026-02-28 23:08:00,Asa Sul,NaN,Acessórios,Suporte Notebook,1,79.9,0.00,36.0,79.90,Dinheiro,Concluído
5181,PED03550,2026-03-08 11:34:00,Asa Sul,NaN,Acessórios,Suporte Notebook,2,79.9,0.00,36.0,159.80,Cartão de Débito,Concluído
5241,PED07633,2026-03-10 16:17:00,Asa Sul,NaN,Informática,Webcam,3,159.9,0.00,88.0,479.70,Cartão de Débito,Concluído
5472,PED03463,2026-03-19 03:17:00,Ceilândia,NaN,Informática,Teclado,2,119.9,0.15,55.0,203.83,Cartão de Crédito,Concluído
6027,PED05688,2026-04-07 22:50:00,Asa Sul,NaN,Eletrônicos,Caixa de Som,1,149.9,0.15,82.0,127.42,Dinheiro,Concluído
6344,PED01347,2026-04-19 00:00:00,Águas Claras,NaN,Informática,Teclado,3,119.9,0.05,55.0,341.72,Cartão de Débito,Concluído
6421,PED02198,2026-04-21 23:55:00,Asa Sul,NaN,Informática,Teclado,3,119.9,0.00,55.0,359.70,PIX,Cancelado
7131,PED09317,2026-05-17 05:12:00,Asa Sul,NaN,Informática,Webcam,2,159.9,0.15,88.0,271.83,Cartão de Crédito,Concluído
7634,PED01954,2026-06-03 19:54:00,Taguatinga,NaN,Acessórios,Carregador,3,59.9,0.15,25.0,152.74,Cartão de Crédito,Concluído
7656,PED01503,2026-06-04 14:55:00,Águas Claras,NaN,Eletrônicos,Caixa de Som,1,149.9,0.00,82.0,149.90,Dinheiro,Concluído
8485,PED02206,2026-07-06 07:50:00,Águas Claras,NaN,Informática,Teclado,1,119.9,0.15,55.0,101.92,Cartão de Crédito,Concluído
9838,PED03901,2026-08-25 22:37:00,Guará,NaN,Acessórios,Carregador,2,59.9,0.00,25.0,119.80,Cartão de Débito,Concluído

Foram identificados 25 registros com id_cliente ausente. Não foi possível determinar a causa da ausência nem reconstruir o identificador a partir das demais informações disponíveis. Para preservar esses registros sem atribuir clientes fictícios, os valores ausentes serão classificados como Não informado.

In [17]:
validacao = df[
    df["desconto"].notnull() &
    (df["quantidade"] > 0) &
    (df["preco_unitario"] > 0)
].copy()

validacao["faturamento_calculado"] = (
    validacao["quantidade"]
    * validacao["preco_unitario"]
    * (1 - validacao["desconto"])
).round(2)

validacao[
    validacao["faturamento"] != validacao["faturamento_calculado"]
][
    ["id_pedido", "quantidade", "preco_unitario",
     "desconto", "faturamento", "faturamento_calculado"]
]

,id_pedido,quantidade,preco_unitario,desconto,faturamento,faturamento_calculado
3,PED09734,1,149.9,0.05,142.41,142.40
6,PED01080,1,119.9,0.05,113.91,113.90
11,PED09430,1,79.9,0.05,75.91,75.90
27,PED09811,1,159.9,0.15,135.91,135.92
47,PED03978,1,159.9,0.15,135.91,135.92
...,...,...,...,...,...,...
9979,PED04411,1,219.9,0.15,186.91,186.92
9981,PED09179,1,219.9,0.15,186.91,186.92
9982,PED03205,1,149.9,0.05,142.41,142.40
10018,PED03861,1,59.9,0.15,50.91,50.92
10025,PED02946,1,89.9,0.05,85.41,85.40

In [18]:
validacao["faturamento"] != validacao["faturamento_calculado"]

0        False
1        False
2        False
3         True
4        False
         ...
10025     True
10026    False
10027    False
10028    False
10029    False
Length: 9995, dtype: bool

In [19]:
validacao["diferenca_faturamento"] = (
    validacao["faturamento"] -
    validacao["faturamento_calculado"]
).abs()

In [20]:
validacao["diferenca_faturamento"].describe()

count    9995.000000
mean        0.001115
std         0.003147
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         0.010000
Name: diferenca_faturamento, dtype: float64

Validação do faturamento: ao comparar o faturamento registrado com o faturamento recalculado a partir da quantidade, preço unitário e desconto, foram observadas pequenas diferenças. A maior divergência encontrada foi de R$ 0,01, indicando diferenças compatíveis com arredondamento, sem evidência de inconsistências relevantes no cálculo do faturamento entre os registros avaliados.


## 4. Limpeza e tratamento
    duplicados
    nulos
    lojas
    quantidade
    preços
    data_hora...

In [21]:
df.shape

(10030, 13)

In [22]:
df = df.drop_duplicates()

In [23]:
df.duplicated().sum()

np.int64(0)

In [24]:
df.shape

(10000, 13)

Tratamento de duplicidades: foram removidos 30 registros completamente duplicados, reduzindo a base de 10.030 para 10.000 registros. Após a remoção, uma nova verificação confirmou a ausência de duplicidades completas.

In [25]:
df['forma_pagamento']= df["forma_pagamento"].fillna("Não Informado")

In [26]:
df["forma_pagamento"].isnull().sum()

np.int64(0)

In [27]:
df["forma_pagamento"].value_counts(dropna=False)

forma_pagamento
Cartão de Débito     2573
PIX                  2507
Dinheiro             2449
Cartão de Crédito    2446
Não Informado          25
Name: count, dtype: int64

In [28]:
df["id_cliente"] = df["id_cliente"].fillna("Não Informado")

In [29]:
df["id_cliente"].isnull().sum()

np.int64(0)

In [30]:
mascara_desconto = df["desconto"].isnull()

In [31]:
mascara_desconto.sum()

np.int64(25)

In [32]:
df.loc[mascara_desconto, "desconto"] = (
    (
        df.loc[mascara_desconto, "quantidade"]
        * df.loc[mascara_desconto, "preco_unitario"]
        - df.loc[mascara_desconto, "faturamento"]
    )
    /
    (
        df.loc[mascara_desconto, "quantidade"]
        * df.loc[mascara_desconto, "preco_unitario"]
    )
).round(2)

In [33]:
df["desconto"].isnull().sum()

np.int64(0)

In [34]:
df["desconto"].value_counts().sort_index()

desconto
0.00    5030
0.05    1572
0.10    1757
0.15    1641
Name: count, dtype: int64

Tratamento dos valores ausentes: os valores ausentes de id_cliente e forma_pagamento foram classificados como Não Informado, pois não havia informações suficientes para reconstruí-los. Já os valores ausentes de desconto foram recalculados a partir da relação entre quantidade, preço unitário e faturamento, preservando a informação financeira disponível nos registro

In [35]:
df["loja"] = df["loja"].replace({
    "aguas claras": "Águas Claras",
    "TAGUATINGA ": "Taguatinga",
    "Asa sul": "Asa Sul"
})

In [36]:
df["loja"].value_counts()

loja
Guará           2040
Taguatinga      1994
Asa Sul         1993
Ceilândia       1989
Águas Claras    1984
Name: count, dtype: int64

Padronização da coluna loja: foram corrigidas variações de escrita, capitalização e acentuação nos nomes das unidades. Após o tratamento, a coluna passou a apresentar cinco categorias padronizadas: Guará, Taguatinga, Asa Sul, Ceilândia e Águas Claras

In [37]:
df[df['quantidade'] <= 0]

,id_pedido,data_hora,loja,id_cliente,categoria,produto,quantidade,preco_unitario,desconto,custo_unitario,faturamento,forma_pagamento,status
621,PED03674,2025-09-21 09:49:00,Asa Sul,CLI1670,Eletrônicos,Fone Bluetooth,0,89.9,0.15,48.0,76.42,Dinheiro,Concluído
2864,PED04159,2025-12-13 19:32:00,Ceilândia,CLI2449,Eletrônicos,Smartwatch,0,219.9,0.00,130.0,879.60,Dinheiro,Concluído
3820,PED04313,2026-01-16 17:09:00,Asa Sul,CLI0490,Acessórios,Cabo USB-C,0,29.9,0.00,11.0,59.80,Cartão de Débito,Concluído
3874,PED09392,2026-01-18 17:15:00,Asa Sul,CLI1541,Informática,Mouse,0,69.9,0.00,31.0,209.70,Cartão de Débito,Concluído
7710,PED00639,2026-06-06 19:42:00,Águas Claras,CLI2294,Informática,Teclado,0,119.9,0.00,55.0,239.80,Dinheiro,Concluído

In [38]:
quantidade_zero = df[df["quantidade"] <= 0].copy()

quantidade_zero["quantidade_calculada"] = (
    quantidade_zero["faturamento"]
    /
    (
        quantidade_zero["preco_unitario"]
        * (1 - quantidade_zero["desconto"])
    )
).round()

In [39]:
quantidade_zero[
    ["produto", "quantidade", "preco_unitario",
     "desconto", "faturamento", "quantidade_calculada"]
]

,produto,quantidade,preco_unitario,desconto,faturamento,quantidade_calculada
621,Fone Bluetooth,0,89.9,0.15,76.42,1.0
2864,Smartwatch,0,219.9,0.00,879.60,4.0
3820,Cabo USB-C,0,29.9,0.00,59.80,2.0
3874,Mouse,0,69.9,0.00,209.70,3.0
7710,Teclado,0,119.9,0.00,239.80,2.0

In [40]:
mascara_quantidade = df["quantidade"] <= 0

df.loc[mascara_quantidade, "quantidade"] = (
    df.loc[mascara_quantidade, "faturamento"]
    /
    (
        df.loc[mascara_quantidade, "preco_unitario"]
        * (1 - df.loc[mascara_quantidade, "desconto"])
    )
).round()

In [41]:
df[df["quantidade"] <= 0]

Empty DataFrame
Columns: [id_pedido, data_hora, loja, id_cliente, categoria, produto, quantidade, preco_unitario, desconto, custo_unitario, faturamento, forma_pagamento, status]
Index: []

Tratamento da coluna quantidade: foram identificados 5 registros com quantidade igual a zero. Como o faturamento, o preço unitário e o desconto estavam disponíveis, foi possível reconstruir a quantidade vendida por meio dessas informações. Após o tratamento, não permaneceram quantidades iguais ou inferiores a zero.

In [42]:
mascara_preco = df["preco_unitario"] < 0

df.loc[mascara_preco, "preco_unitario"] = (
    df.loc[mascara_preco, "preco_unitario"].abs()
)

In [43]:
df[df["preco_unitario"] <= 0]

Empty DataFrame
Columns: [id_pedido, data_hora, loja, id_cliente, categoria, produto, quantidade, preco_unitario, desconto, custo_unitario, faturamento, forma_pagamento, status]
Index: []

Tratamento da coluna preco_unitario: foram identificados 5 registros com preços unitários negativos. Após a análise dos registros e comparação com os demais dados das vendas, verificou-se que a inconsistência estava relacionada ao sinal dos valores. Os preços negativos foram corrigidos utilizando seu valor absoluto (abs()), preservando o valor original do produto. Após o tratamento, foi realizada uma nova validação e não foram encontrados preços unitários iguais ou inferiores a zero.

In [44]:
df["data_hora"] = pd.to_datetime(df["data_hora"])

In [45]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_pedido        10000 non-null  str
 1   data_hora        10000 non-null  datetime64[us]
 2   loja             10000 non-null  str
 3   id_cliente       10000 non-null  str
 4   categoria        10000 non-null  str
 5   produto          10000 non-null  str
 6   quantidade       10000 non-null  int64
 7   preco_unitario   10000 non-null  float64
 8   desconto         10000 non-null  float64
 9   custo_unitario   10000 non-null  float64
 10  faturamento      10000 non-null  float64
 11  forma_pagamento  10000 non-null  str
 12  status           10000 non-null  str
dtypes: datetime64[us](1), float64(4), int64(1), str(7)
memory usage: 1015.8 KB

Tratamento da coluna data_hora: a coluna estava armazenada como texto (str), o que dificultaria análises temporais. Os valores foram convertidos para o tipo datetime, permitindo a utilização adequada das informações de data e horário em análises posteriores, como evolução mensal do faturamento, desempenho por período e identificação de tendências.

## 5. Validação final

In [46]:
print("Dimensão da base:", df.shape)
print("Duplicados:", df.duplicated().sum())
print("Valores nulos:", df.isnull().sum().sum())
print("Quantidades inválidas:", (df["quantidade"] <= 0).sum())
print("Preços inválidos:", (df["preco_unitario"] <= 0).sum())
print("Tipo data_hora:", df["data_hora"].dtype)

Dimensão da base: (10000, 13)
Duplicados: 0
Valores nulos: 0
Quantidades inválidas: 0
Preços inválidos: 0
Tipo data_hora: datetime64[us]

## 6. Exportação dos dados tratados
    df.to_csv(...)

In [47]:
df.to_csv(
    "Dados/Tratado/vendas_tratadas.csv",
    index=False,
    encoding="utf-8-sig"
)

## 7. Análise Financeira e KPIs

Análise Financeira e KPIs

A partir desta etapa, as análises serão realizadas utilizando a base tratada após o processo de ETL.

O objetivo é calcular e analisar os principais indicadores financeiros e comerciais, identificando tendências, variações de desempenho e possíveis pontos de atenção.

In [48]:
df = pd.read_csv(
    "Dados/Tratado/vendas_tratadas.csv",
    parse_dates=["data_hora"]
)

In [49]:
df["status"].value_counts()

status
Concluído    9394
Cancelado     411
Devolvido     195
Name: count, dtype: int64

In [50]:
df.groupby("status")["faturamento"].sum()

status
Cancelado      79877.74
Concluído    1835037.86
Devolvido      37612.78
Name: faturamento, dtype: float64

## Seção 8 — Definição das Regras de Negócio

Já definimos que Cancelado não pode entrar no faturamento realizado. Para Devolvido, vamos adotar uma regra simples para este projeto: também não entra no faturamento realizado, porque aquela venda não permaneceu efetivada. Mais adiante, podemos analisar devoluções separadamente como um indicador.

In [51]:
df_concluido = df[df["status"] == "Concluído"].copy()

In [52]:
df_concluido["status"].value_counts()

status
Concluído    9394
Name: count, dtype: int64

In [53]:
df_concluido["faturamento"].sum()

np.float64(1835037.86)

## Seção 9 — Criação das Métricas Financeiras.

## 9.1 Custo total

In [54]:
df_concluido["custo_total"] = (
    df_concluido["quantidade"] * df_concluido["custo_unitario"]
)

In [55]:
df_concluido[
    [
        "produto",
        "quantidade",
        "preco_unitario",
        "desconto",
        "custo_unitario",
        "custo_total",
        "faturamento"
    ]
].head(10)

,produto,quantidade,preco_unitario,desconto,custo_unitario,custo_total,faturamento
0,Smartwatch,2,219.9,0.15,130.0,260.0,373.83
1,Webcam,4,159.9,0.00,88.0,352.0,639.60
2,Teclado,3,119.9,0.05,55.0,165.0,341.72
3,Caixa de Som,1,149.9,0.05,82.0,82.0,142.41
4,Suporte Notebook,1,79.9,0.00,36.0,36.0,79.90
5,Fone Bluetooth,1,89.9,0.00,48.0,48.0,89.90
6,Teclado,1,119.9,0.05,55.0,55.0,113.91
7,Webcam,4,159.9,0.10,88.0,352.0,575.64
8,Smartwatch,1,219.9,0.00,130.0,130.0,219.90
9,Fone Bluetooth,4,89.9,0.15,48.0,192.0,305.66

## 9.2 Lucro Bruto

In [56]:
df_concluido["lucro_bruto"] = (
    df_concluido["faturamento"] - df_concluido["custo_total"]
)

In [57]:
df_concluido[
    [
        "produto",
        "quantidade",
        "faturamento",
        "custo_total",
        "lucro_bruto"
    ]
].head(10)

            produto  quantidade  faturamento  custo_total  lucro_bruto
0        Smartwatch           2       373.83        260.0       113.83
1            Webcam           4       639.60        352.0       287.60
2           Teclado           3       341.72        165.0       176.72
3      Caixa de Som           1       142.41         82.0        60.41
4  Suporte Notebook           1        79.90         36.0        43.90
5    Fone Bluetooth           1        89.90         48.0        41.90
6           Teclado           1       113.91         55.0        58.91
7            Webcam           4       575.64        352.0       223.64
8        Smartwatch           1       219.90        130.0        89.90
9    Fone Bluetooth           4       305.66        192.0       113.66

# 9.3 Margem Bruta

In [58]:
df_concluido["margem_bruta"] = (
    df_concluido["lucro_bruto"]
    / df_concluido["faturamento"]
    * 100
).round(2)

In [59]:
df_concluido[
    [
        "produto",
        "faturamento",
        "custo_total",
        "lucro_bruto",
        "margem_bruta"
    ]
].head(10)

            produto  faturamento  custo_total  lucro_bruto  margem_bruta
0        Smartwatch       373.83        260.0       113.83         30.45
1            Webcam       639.60        352.0       287.60         44.97
2           Teclado       341.72        165.0       176.72         51.71
3      Caixa de Som       142.41         82.0        60.41         42.42
4  Suporte Notebook        79.90         36.0        43.90         54.94
5    Fone Bluetooth        89.90         48.0        41.90         46.61
6           Teclado       113.91         55.0        58.91         51.72
7            Webcam       575.64        352.0       223.64         38.85
8        Smartwatch       219.90        130.0        89.90         40.88
9    Fone Bluetooth       305.66        192.0       113.66         37.19

## Seção 10 — Indicadores Financeiros (KPIs)

KPI: Faturamento Total das vendas concluídas.

In [60]:
faturamento_total = df_concluido["faturamento"].sum()

faturamento_total

np.float64(1835037.86)

In [61]:
print(f"Faturamento Total: R$ {faturamento_total:,.2f}")

Faturamento Total: R$ 1,835,037.86

KPI: Custo Total da operação

In [62]:
custo_total = df_concluido["custo_total"].sum()

print(f"Custo Total: R$ {custo_total:,.2f}")

Custo Total: R$ 1,000,593.00

In [63]:
lucro_total_bruto = df_concluido["lucro_bruto"].sum()

print(f"Lucro Total Bruto: R$ {lucro_total_bruto:,.2f}")

Lucro Total Bruto: R$ 834,444.86

KPI: Margem Bruta Geral

In [64]:
margem_bruta_geral = (
    lucro_total_bruto / faturamento_total * 100
)

print(f"Margem Bruta Geral: {margem_bruta_geral:.2f}%")

Margem Bruta Geral: 45.47%

KPI : Ticket Médio.

In [65]:
quantidade_pedidos = df_concluido["id_pedido"].nunique()

In [66]:
quantidade_pedidos

9394

In [67]:
ticket_medio = faturamento_total / quantidade_pedidos

print(f"Ticket Médio: R$ {ticket_medio:,.2f}")

Ticket Médio: R$ 195.34

KPI: Quantidade de produtos vendidos

In [68]:
unidades_vendidas = df_concluido["quantidade"].sum()

print(f"Unidades vendidas: {unidades_vendidas}")

Unidades vendidas: 17609

KPI: Desconto Concedido em R$

In [69]:
df_concluido["desconto_reais"] = (
    df_concluido["quantidade"]
    * df_concluido["preco_unitario"]
    * df_concluido["desconto"]
).round(2)

desconto_total_reais = df_concluido["desconto_reais"].sum()

print(f"Desconto concedido: R$ {desconto_total_reais:,.2f}")

Desconto concedido: R$ 96,998.99

## Seção 11 — Análise Temporal

11.1 Criando a coluna de mês

In [70]:
df_concluido["mes"] = (
    df_concluido["data_hora"].dt.to_period("M")
)

11.2 Faturamento mensal

In [71]:
df_concluido[
    ["data_hora", "mes", "faturamento"]
].head(10)

            data_hora      mes  faturamento
0 2025-09-01 02:45:00  2025-09       373.83
1 2025-09-01 03:23:00  2025-09       639.60
2 2025-09-01 03:39:00  2025-09       341.72
3 2025-09-01 05:00:00  2025-09       142.41
4 2025-09-01 06:20:00  2025-09        79.90
5 2025-09-01 08:22:00  2025-09        89.90
6 2025-09-01 09:12:00  2025-09       113.91
7 2025-09-01 09:33:00  2025-09       575.64
8 2025-09-01 11:17:00  2025-09       219.90
9 2025-09-01 11:47:00  2025-09       305.66

In [72]:
faturamento_mensal = (
    df_concluido
    .groupby("mes")["faturamento"]
    .sum()
)

faturamento_mensal

mes
2025-09    157553.69
2025-10    154911.99
2025-11    146847.66
2025-12    154742.06
2026-01    168067.95
2026-02    123584.37
2026-03    154981.76
2026-04    163538.70
2026-05    155721.91
2026-06    149864.19
2026-07    144920.27
2026-08    160303.31
Freq: M, Name: faturamento, dtype: float64

11.3 Resumo financeiro mensal

In [73]:
resumo_financeiro_mensal = (
    df_concluido
    .groupby("mes")
    .agg(
        faturamento=("faturamento", "sum"),
        custo_total=("custo_total", "sum"),
        lucro_bruto=("lucro_bruto", "sum"),
        
    )
)

In [74]:
resumo_financeiro_mensal

         faturamento  custo_total  lucro_bruto
mes
2025-09    157553.69      85338.0     72215.69
2025-10    154911.99      83744.0     71167.99
2025-11    146847.66      79807.0     67040.66
2025-12    154742.06      84502.0     70240.06
2026-01    168067.95      91753.0     76314.95
2026-02    123584.37      67474.0     56110.37
2026-03    154981.76      84552.0     70429.76
2026-04    163538.70      90009.0     73529.70
2026-05    155721.91      84968.0     70753.91
2026-06    149864.19      81943.0     67921.19
2026-07    144920.27      78564.0     66356.27
2026-08    160303.31      87939.0     72364.31

In [75]:
resumo_financeiro_mensal["margem_bruta"] = (
    resumo_financeiro_mensal["lucro_bruto"]
    / resumo_financeiro_mensal["faturamento"]
    * 100
).round(2)

resumo_financeiro_mensal[["faturamento", "lucro_bruto", "margem_bruta"]]

         faturamento  lucro_bruto  margem_bruta
mes
2025-09    157553.69     72215.69         45.84
2025-10    154911.99     71167.99         45.94
2025-11    146847.66     67040.66         45.65
2025-12    154742.06     70240.06         45.39
2026-01    168067.95     76314.95         45.41
2026-02    123584.37     56110.37         45.40
2026-03    154981.76     70429.76         45.44
2026-04    163538.70     73529.70         44.96
2026-05    155721.91     70753.91         45.44
2026-06    149864.19     67921.19         45.32
2026-07    144920.27     66356.27         45.79
2026-08    160303.31     72364.31         45.14

11.4 Variação mensal do faturamento

In [76]:
resumo_financeiro_mensal["variacao_faturamento"] = (
    resumo_financeiro_mensal["faturamento"]
    .pct_change()
    .mul(100)
    .round(2)
)

In [77]:
resumo_financeiro_mensal[
    ["faturamento", "variacao_faturamento"]
]

         faturamento  variacao_faturamento
mes
2025-09    157553.69                   NaN
2025-10    154911.99                 -1.68
2025-11    146847.66                 -5.21
2025-12    154742.06                  5.38
2026-01    168067.95                  8.61
2026-02    123584.37                -26.47
2026-03    154981.76                 25.41
2026-04    163538.70                  5.52
2026-05    155721.91                 -4.78
2026-06    149864.19                 -3.76
2026-07    144920.27                 -3.30
2026-08    160303.31                 10.61

11.5 Melhor e pior mês em faturamento

In [78]:
mes_maior_faturamento = resumo_financeiro_mensal["faturamento"].idxmax()

maior_faturamento = resumo_financeiro_mensal["faturamento"].max()

print(f"Mês com maior faturamento: {mes_maior_faturamento}")
print(f"Faturamento: R$ {maior_faturamento:,.2f}")

Mês com maior faturamento: 2026-01
Faturamento: R$ 168,067.95

In [79]:
mes_menor_faturamento = resumo_financeiro_mensal["faturamento"].idxmin()

menor_faturamento = resumo_financeiro_mensal["faturamento"].min()

print(f"Mês com menor faturamento: {mes_menor_faturamento}")
print(f"Faturamento: R$ {menor_faturamento:,.2f}")

Mês com menor faturamento: 2026-02
Faturamento: R$ 123,584.37

## 12. Análise por Loja

In [80]:
resumo_lojas =(
    df_concluido
    .groupby("loja")
    .agg(
        faturamento=("faturamento", "sum"),
        custo_total=("custo_total", "sum"),
        lucro_bruto=("lucro_bruto", "sum"),
    )
)

In [81]:
resumo_lojas

              faturamento  custo_total  lucro_bruto
loja
Asa Sul         373865.01     204591.0    169274.01
Ceilândia       362642.81     198329.0    164313.81
Guará           368513.95     199865.0    168648.95
Taguatinga      360977.78     196363.0    164614.78
Águas Claras    369038.31     201445.0    167593.31

In [82]:
resumo_lojas["margem_bruta"] = (
    resumo_lojas["lucro_bruto"] / resumo_lojas["faturamento"]
   * 100
).round(2)

resumo_lojas

              faturamento  custo_total  lucro_bruto  margem_bruta
loja
Asa Sul         373865.01     204591.0    169274.01         45.28
Ceilândia       362642.81     198329.0    164313.81         45.31
Guará           368513.95     199865.0    168648.95         45.76
Taguatinga      360977.78     196363.0    164614.78         45.60
Águas Claras    369038.31     201445.0    167593.31         45.41

In [83]:
loja_maior_faturamento = resumo_lojas["faturamento"].idxmax()
loja_maior_lucro = resumo_lojas["lucro_bruto"].idxmax()
loja_maior_margem = resumo_lojas["margem_bruta"].idxmax()

print(f"Loja com maior faturamento: {loja_maior_faturamento}")
print(f"Loja com maior lucro bruto: {loja_maior_lucro}")
print(f"Loja com maior margem bruta: {loja_maior_margem}")

Loja com maior faturamento: Asa Sul
Loja com maior lucro bruto: Asa Sul
Loja com maior margem bruta: Guará

In [84]:
valor_maior_faturamento = resumo_lojas.loc[
    loja_maior_faturamento, "faturamento"
]

valor_maior_lucro = resumo_lojas.loc[
    loja_maior_lucro, "lucro_bruto"
]

valor_maior_margem = resumo_lojas.loc[
    loja_maior_margem, "margem_bruta"
]

print(
    f"Maior faturamento: {loja_maior_faturamento} - "
    f"R$ {valor_maior_faturamento:,.2f}"
)

print(
    f"Maior lucro bruto: {loja_maior_lucro} - "
    f"R$ {valor_maior_lucro:,.2f}"
)

print(
    f"Maior margem bruta: {loja_maior_margem} - "
    f"{valor_maior_margem:.2f}%"
)

Maior faturamento: Asa Sul - R$ 373,865.01
Maior lucro bruto: Asa Sul - R$ 169,274.01
Maior margem bruta: Guará - 45.76%

## Seção 13 — Análise por Categoria e Produto

13. Análise por Categoria e Produto

Nesta etapa, será analisado o desempenho financeiro das categorias e dos produtos, considerando faturamento, custo, lucro bruto, margem bruta e quantidade vendida.

O objetivo é identificar quais produtos e categorias possuem maior participação nos resultados e quais apresentam maior rentabilidade.

In [85]:
resumo_categorias =(
    df_concluido
    .groupby("categoria")
    .agg(
        faturamento=("faturamento", "sum"),
        custo_total=("custo_total", "sum"),
        lucro_bruto=("lucro_bruto", "sum"),
        unidades_vendidas=("quantidade", "sum")
    )
)

In [86]:
resumo_categorias = resumo_categorias.sort_values(
    "faturamento",
    ascending=False
)

resumo_categorias

             faturamento  custo_total  lucro_bruto  unidades_vendidas
categoria
Eletrônicos    886850.65     527506.0    359344.65               6058
Informática    639558.43     335738.0    303820.43               5786
Acessórios     308628.78     137349.0    171279.78               5765

In [87]:
resumo_categorias["margem_bruta"] = (
    resumo_categorias["lucro_bruto"]
    / resumo_categorias["faturamento"]
    * 100
).round(2)

resumo_categorias

,faturamento,custo_total,lucro_bruto,unidades_vendidas,margem_bruta
categoria,,,,,
Eletrônicos,886850.65,527506.0,359344.65,6058,40.52
Informática,639558.43,335738.0,303820.43,5786,47.50
Acessórios,308628.78,137349.0,171279.78,5765,55.50

In [88]:
categoria_maior_faturamento = resumo_categorias["faturamento"].idxmax()
categoria_maior_lucro = resumo_categorias["lucro_bruto"].idxmax()
categoria_maior_margem = resumo_categorias["margem_bruta"].idxmax()

print(
    f"Maior faturamento: {categoria_maior_faturamento} - "
    f"R$ {resumo_categorias.loc[categoria_maior_faturamento, 'faturamento']:,.2f}"
)

print(
    f"Maior lucro bruto: {categoria_maior_lucro} - "
    f"R$ {resumo_categorias.loc[categoria_maior_lucro, 'lucro_bruto']:,.2f}"
)

print(
    f"Maior margem bruta: {categoria_maior_margem} - "
    f"{resumo_categorias.loc[categoria_maior_margem, 'margem_bruta']:.2f}%"
)

Maior faturamento: Eletrônicos - R$ 886,850.65
Maior lucro bruto: Eletrônicos - R$ 359,344.65
Maior margem bruta: Acessórios - 55.50%

In [89]:
resumo_produtos =(
    df_concluido
    .groupby("produto")
    .agg(
        faturamento=("faturamento", "sum"),
        custo_total=("custo_total", "sum"),
        lucro_bruto=("lucro_bruto", "sum"),
        unidades_vendidas=("quantidade", "sum")
    )
)

In [90]:
resumo_produtos = resumo_produtos.sort_values(
    "faturamento",
    ascending=False
)

resumo_produtos

                  faturamento  custo_total  lucro_bruto  unidades_vendidas
produto
Smartwatch          423109.73     263120.0    159989.73               2024
Caixa de Som        296795.54     170642.0    126153.54               2081
Webcam              290042.80     168608.0    121434.80               1916
Teclado             223027.01     108075.0    114952.01               1965
Fone Bluetooth      166945.38      93744.0     73201.38               1953
Suporte Notebook    138419.98      65520.0     72899.98               1820
Mouse               126488.62      59055.0     67433.62               1905
Carregador          115890.43      50775.0     65115.43               2031
Cabo USB-C           54318.37      21054.0     33264.37               1914

In [91]:
resumo_produtos["margem_bruta"] = (
    resumo_produtos["lucro_bruto"]
    / resumo_produtos["faturamento"]
    * 100
).round(2)

resumo_produtos[["faturamento", "lucro_bruto", "margem_bruta"]]

                  faturamento  lucro_bruto  margem_bruta
produto
Smartwatch          423109.73    159989.73         37.81
Caixa de Som        296795.54    126153.54         42.51
Webcam              290042.80    121434.80         41.87
Teclado             223027.01    114952.01         51.54
Fone Bluetooth      166945.38     73201.38         43.85
Suporte Notebook    138419.98     72899.98         52.67
Mouse               126488.62     67433.62         53.31
Carregador          115890.43     65115.43         56.19
Cabo USB-C           54318.37     33264.37         61.24

In [92]:
produto_maior_faturamento = resumo_produtos["faturamento"].idxmax()
produto_maior_lucro = resumo_produtos["lucro_bruto"].idxmax()
produto_maior_margem = resumo_produtos["margem_bruta"].idxmax()

print(
    f"Maior faturamento: {produto_maior_faturamento} - "
    f"R$ {resumo_produtos.loc[produto_maior_faturamento, 'faturamento']:,.2f}"
)

print(
    f"Maior lucro bruto: {produto_maior_lucro} - "
    f"R$ {resumo_produtos.loc[produto_maior_lucro, 'lucro_bruto']:,.2f}"
)

print(
    f"Maior margem bruta: {produto_maior_margem} - "
    f"{resumo_produtos.loc[produto_maior_margem, 'margem_bruta']:.2f}%"
)

Maior faturamento: Smartwatch - R$ 423,109.73
Maior lucro bruto: Smartwatch - R$ 159,989.73
Maior margem bruta: Cabo USB-C - 61.24%

## Seção 14 — Preparação dos Dados para o Power BI.

In [93]:
df_powerbi = df.copy()

df_powerbi["custo_total"] = (
    df_powerbi["quantidade"] * df_powerbi["custo_unitario"]
)

df_powerbi["desconto_reais"] = (
    df_powerbi["quantidade"]
    * df_powerbi["preco_unitario"]
    * df_powerbi["desconto"]
).round(2)

In [94]:
df_powerbi

,id_pedido,data_hora,loja,id_cliente,categoria,produto,quantidade,preco_unitario,desconto,custo_unitario,faturamento,forma_pagamento,status,custo_total,desconto_reais
0,PED00964,2025-09-01 02:45:00,Taguatinga,CLI1729,Eletrônicos,Smartwatch,2,219.9,0.15,130.0,373.83,PIX,Concluído,260.0,65.97
1,PED08693,2025-09-01 03:23:00,Taguatinga,CLI0203,Informática,Webcam,4,159.9,0.00,88.0,639.60,PIX,Concluído,352.0,0.00
2,PED02240,2025-09-01 03:39:00,Taguatinga,CLI1118,Informática,Teclado,3,119.9,0.05,55.0,341.72,Cartão de Crédito,Concluído,165.0,17.99
3,PED09734,2025-09-01 05:00:00,Asa Sul,CLI1717,Eletrônicos,Caixa de Som,1,149.9,0.05,82.0,142.41,PIX,Concluído,82.0,7.50
4,PED09063,2025-09-01 06:20:00,Águas Claras,CLI0478,Acessórios,Suporte Notebook,1,79.9,0.00,36.0,79.90,PIX,Concluído,36.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,PED03190,2026-08-31 19:46:00,Taguatinga,CLI1716,Informática,Teclado,1,119.9,0.10,55.0,107.91,PIX,Concluído,55.0,11.99
9996,PED09273,2026-08-31 20:09:00,Águas Claras,CLI0032,Informática,Teclado,4,119.9,0.00,55.0,479.60,Cartão de Crédito,Concluído,220.0,0.00
9997,PED09815,2026-08-31 22:15:00,Asa Sul,CLI0507,Acessórios,Carregador,2,59.9,0.10,25.0,107.82,Cartão de Débito,Concluído,50.0,11.98
9998,PED04798,2026-08-31 22:46:00,Guará,CLI0175,Eletrônicos,Smartwatch,1,219.9,0.00,130.0,219.90,Dinheiro,Concluído,130.0,0.00
9999,PED04984,2026-08-31 23:47:00,Taguatinga,CLI0853,Acessórios,Cabo USB-C,1,29.9,0.00,11.0,29.90,PIX,Devolvido,11.0,0.00

In [95]:
df_powerbi["faturamento_realizado"] = (
    df_powerbi["faturamento"]
    .where(df_powerbi["status"] == "Concluído", 0)
)

df_powerbi["custo_realizado"] = (
    df_powerbi["custo_total"]
    .where(df_powerbi["status"] == "Concluído", 0)
)

df_powerbi["lucro_bruto_realizado"] = (
    df_powerbi["faturamento_realizado"]
    - df_powerbi["custo_realizado"]
)

In [96]:
df_powerbi[
    [
        "status",
        "faturamento",
        "faturamento_realizado",
        "custo_realizado",
        "lucro_bruto_realizado"
    ]
].head(20)

,status,faturamento,faturamento_realizado,custo_realizado,lucro_bruto_realizado
0,Concluído,373.83,373.83,260.0,113.83
1,Concluído,639.60,639.60,352.0,287.60
2,Concluído,341.72,341.72,165.0,176.72
3,Concluído,142.41,142.41,82.0,60.41
4,Concluído,79.90,79.90,36.0,43.90
5,Concluído,89.90,89.90,48.0,41.90
6,Concluído,113.91,113.91,55.0,58.91
7,Concluído,575.64,575.64,352.0,223.64
8,Concluído,219.90,219.90,130.0,89.90
9,Concluído,305.66,305.66,192.0,113.66
10,Concluído,239.80,239.80,110.0,129.80
11,Concluído,75.91,75.91,36.0,39.91
12,Concluído,69.90,69.90,31.0,38.90
13,Concluído,269.70,269.70,144.0,125.70
14,Devolvido,599.60,0.00,0.0,0.00
15,Concluído,239.60,239.60,100.0,139.60
16,Concluído,159.90,159.90,88.0,71.90
17,Cancelado,219.90,0.00,0.0,0.00
18,Concluído,359.60,359.60,192.0,167.60
19,Concluído,29.90,29.90,11.0,18.90

In [97]:
df_powerbi.shape

(10000, 18)

In [98]:
df_powerbi[
    [
        "faturamento_realizado",
        "custo_realizado",
        "lucro_bruto_realizado"
    ]
].sum()

faturamento_realizado    1835037.86
custo_realizado          1000593.00
lucro_bruto_realizado     834444.86
dtype: float64

In [99]:
df_powerbi.to_csv(
    "Dados/PowerBI/base_financeira_powerbi.csv",
    index=False,
    encoding="utf-8-sig"
)

# Análise Inteligente com IA

Nesta etapa, os indicadores calculados anteriormente serão utilizados
para gerar insights automáticos sobre o desempenho financeiro do negócio.

In [100]:
contexto_financeiro = {
    "faturamento_total": faturamento_total,
    "custo_total": custo_total,
    "lucro_bruto": lucro_total_bruto,
    "margem_bruta": margem_bruta_geral,
    "maior_faturamento_mensal": maior_faturamento,
    "menor_faturamento_mensal": menor_faturamento,
    "mes_maior_faturamento": str(mes_maior_faturamento),
    "mes_menor_faturamento": str(mes_menor_faturamento),
    "loja_maior_faturamento": loja_maior_faturamento,
    "loja_maior_lucro": loja_maior_lucro,
    "loja_maior_margem": loja_maior_margem,
    "categoria_maior_faturamento": categoria_maior_faturamento,
    "categoria_maior_lucro": categoria_maior_lucro,
    "categoria_maior_margem": categoria_maior_margem
}

contexto_financeiro

{'faturamento_total': np.float64(1835037.86),
 'custo_total': np.float64(1000593.0),
 'lucro_bruto': np.float64(834444.8599999999),
 'margem_bruta': np.float64(45.472896128693485),
 'maior_faturamento_mensal': np.float64(168067.95),
 'menor_faturamento_mensal': np.float64(123584.37),
 'mes_maior_faturamento': '2026-01',
 'mes_menor_faturamento': '2026-02',
 'loja_maior_faturamento': 'Asa Sul',
 'loja_maior_lucro': 'Asa Sul',
 'loja_maior_margem': 'Guará',
 'categoria_maior_faturamento': 'Eletrônicos',
 'categoria_maior_lucro': 'Eletrônicos',
 'categoria_maior_margem': 'Acessórios'}

In [101]:
texto_contexto = f"""
RELATÓRIO FINANCEIRO - LUMETRA

INDICADORES GERAIS
- Faturamento total: R$ {contexto_financeiro['faturamento_total']:,.2f}
- Custo total: R$ {contexto_financeiro['custo_total']:,.2f}
- Lucro bruto: R$ {contexto_financeiro['lucro_bruto']:,.2f}
- Margem bruta: {contexto_financeiro['margem_bruta']:.2f}%

DESEMPENHO MENSAL
- Maior faturamento: {contexto_financeiro['mes_maior_faturamento']} - R$ {contexto_financeiro['maior_faturamento_mensal']:,.2f}
- Menor faturamento: {contexto_financeiro['mes_menor_faturamento']} - R$ {contexto_financeiro['menor_faturamento_mensal']:,.2f}

DESTAQUES POR LOJA
- Maior faturamento: {contexto_financeiro['loja_maior_faturamento']}
- Maior lucro: {contexto_financeiro['loja_maior_lucro']}
- Maior margem: {contexto_financeiro['loja_maior_margem']}

DESTAQUES POR CATEGORIA
- Maior faturamento: {contexto_financeiro['categoria_maior_faturamento']}
- Maior lucro: {contexto_financeiro['categoria_maior_lucro']}
- Maior margem: {contexto_financeiro['categoria_maior_margem']}
"""

print(texto_contexto)

RELATÓRIO FINANCEIRO - LUMETRA

INDICADORES GERAIS
- Faturamento total: R$ 1,835,037.86
- Custo total: R$ 1,000,593.00
- Lucro bruto: R$ 834,444.86
- Margem bruta: 45.47%

DESEMPENHO MENSAL
- Maior faturamento: 2026-01 - R$ 168,067.95
- Menor faturamento: 2026-02 - R$ 123,584.37

DESTAQUES POR LOJA
- Maior faturamento: Asa Sul
- Maior lucro: Asa Sul
- Maior margem: Guará

DESTAQUES POR CATEGORIA
- Maior faturamento: Eletrônicos
- Maior lucro: Eletrônicos
- Maior margem: Acessórios

In [102]:
import os
from dotenv import load_dotenv
from google import genai

load_dotenv()

api_key = os.getenv("GEMINI_API_KEY")

if not api_key:
    raise ValueError("GEMINI_API_KEY não encontrada no arquivo .env")

client = genai.Client(api_key=api_key)

print("Gemini conectado com sucesso!")

Gemini conectado com sucesso!

In [103]:
print("MODELOS DISPONÍVEIS PARA SUA API:\n")

for modelo in client.models.list():
    if "generateContent" in modelo.supported_actions:
        print(modelo.name)

MODELOS DISPONÍVEIS PARA SUA API:

models/gemini-2.5-flash
models/gemini-2.5-pro
models/gemini-2.5-flash-preview-tts
models/gemini-2.5-pro-preview-tts
models/gemma-4-26b-a4b-it
models/gemma-4-31b-it
models/gemini-flash-latest
models/gemini-flash-lite-latest
models/gemini-pro-latest
models/gemini-2.5-flash-lite
models/gemini-2.5-flash-image
models/gemini-3-flash-preview
models/gemini-3.1-pro-preview
models/gemini-3.1-pro-preview-customtools
models/gemini-3.1-flash-lite-preview
models/gemini-3.1-flash-lite
models/gemini-3-pro-image-preview
models/gemini-3-pro-image
models/nano-banana-pro-preview
models/gemini-3.1-flash-image-preview
models/gemini-3.1-flash-image
models/gemini-3.1-flash-lite-image
models/gemini-3.5-flash
models/gemini-3.5-flash-lite
models/gemini-omni-flash-preview
models/gemini-omni-1.1-flash
models/gemini-3.5-transcribe
models/gemini-3.6-flash
models/gemini-3.7-flash
models/gemini-3.8-flash
models/lyria-3-clip-preview
models/lyria-3-pro-preview
models/lyria-3.5
models/gemini-3.1-flash-tts-preview
models/gemini-3.8-flash-tts
models/gemini-3.8-flash-lite-tts
models/gemini-robotics-er-2-preview
models/gemini-2.5-computer-use-preview-10-2025
models/antigravity-preview-05-2026
models/antigravity-preview-09-2026
models/antigravity-preview-latest
models/deep-research-max-preview-04-2026
models/deep-research-preview-04-2026
models/deep-research-pro-preview-12-2025

In [104]:
resposta = client.models.generate_content(
    model="models/gemini-3.5-flash",
    contents="Explique em uma frase o que é o Lumetra."
)

print(resposta.text)

Direct use of automatic function calling (AFC) in Models.generate_content is not recommended. Instead, we recommend to use AFC in Chat.send_message. Similarly, direct use of AFC in Models.generate_content_stream is not recommended. Instead, we recommend to use AFC in Chat.send_message_stream.

A **Lumetra** é uma organização de consultoria em saúde que auxilia instituições e governos a melhorar a qualidade do atendimento médico, a segurança do paciente e a eficiência operacional por meio de análise de dados e orientações regulatórias.

In [106]:
prompt_ia = f"""
Você é um analista financeiro.

Analise os dados abaixo referentes ao negócio Lumetra.

{texto_contexto}

Gere uma análise objetiva contendo:

1. Resumo do desempenho financeiro
2. Principais pontos positivos
3. Pontos que merecem atenção
4. Destaques por loja
5. Destaques por categoria
6. Uma conclusão executiva

Não invente informações que não estejam presentes nos dados.
Use somente os números e informações fornecidos.
"""

resposta = client.models.generate_content(
    model="models/gemini-3.5-flash",
    contents=prompt_ia
)

print(resposta.text)

Como analista financeiro, apresento a análise de desempenho do negócio Lumetra com base nos dados fornecidos:

---

### 1. Resumo do Desempenho Financeiro
No período analisado, a Lumetra registrou um **faturamento total de R$ 1.835.037,86**. Diante de um **custo total de R$ 1.000.593,00**, a empresa gerou um **lucro bruto de R$ 834.444,86**, o que representa uma **margem bruta consolidada de 45,47%**.

### 2. Principais Pontos Positivos
* **Margem Bruta Saudável:** A empresa opera com uma margem bruta expressiva de 45,47%, demonstrando um bom retorno sobre o custo dos produtos/serviços vendidos.
* **Pico de Vendas:** O mês de janeiro de 2026 (2026-01) registrou o melhor desempenho do período, com um faturamento de R$ 168.067,95.
* **Sinergia de Volume e Margem:** A empresa possui geradores claros de volume de receita (como a loja Asa Sul e a categoria Eletrônicos) combinados com nichos de alta eficiência de rentabilidade (loja Guará e categoria Acessórios).

### 3. Pontos que Merecem Atenção
* **Volatilidade Mensal:** Identifica-se uma oscilação significativa entre o melhor e o pior mês. Logo após o pico em janeiro de 2026, o faturamento registrou uma queda em fevereiro de 2026 (2026-02), atingindo o menor valor do período (R$ 123.584,37).
* **Peso dos Custos:** O custo total acumulado (R$ 1.000.593,00) representa a maior fatia do faturamento (aproximadamente 54,53%), exigindo atenção contínua para evitar a erosão da margem bruta.

### 4. Destaques por Loja
* **Asa Sul:** Consolida-se como a unidade mais importante em termos de volume e resultado absoluto, liderando tanto em **maior faturamento** quanto em **maior lucro**.
* **Guará:** Destaca-se pela eficiência operacional, registrando a **maior margem** percentual entre as lojas.

### 5. Destaques por Categoria
* **Eletrônicos:** É o principal motor financeiro da Lumetra, responsável pelo **maior faturamento** e pelo **maior lucro** absoluto.
* **Acessórios:** Apresenta-se como a categoria mais eficiente do portfólio, registrando a **maior margem** percentual.

### 6. Conclusão Executiva
A Lumetra demonstra solidez financeira, sustentada por uma margem bruta de 45,47% e faturamento superior a R$ 1,8 milhão. A estratégia do negócio se apoia em dois pilares bem definidos: o volume gerado pela loja Asa Sul e pela categoria de Eletrônicos, e a alta rentabilidade percentual (margem) entregue pela loja Guará e pela categoria de Acessórios.

Para assegurar o crescimento sustentável, a gestão deve focar no controle dos custos totais e na compreensão das causas que levaram à retração de faturamento entre janeiro e fevereiro de 2026, buscando estabilizar a receita mensal.

In [107]:
import json

prompt_json = f"""
Você é um analista financeiro.

Analise os dados financeiros da Lumetra abaixo:

{texto_contexto}

Retorne SOMENTE um JSON válido, sem explicações antes ou depois.

Use exatamente esta estrutura:

{{
    "resumo": "Resumo objetivo do desempenho financeiro",
    "pontos_positivos": [
        "Ponto positivo 1",
        "Ponto positivo 2",
        "Ponto positivo 3"
    ],
    "pontos_atencao": [
        "Ponto de atenção 1",
        "Ponto de atenção 2"
    ],
    "lojas": {{
        "maior_faturamento": "Nome da loja",
        "maior_lucro": "Nome da loja",
        "maior_margem": "Nome da loja"
    }},
    "categorias": {{
        "maior_faturamento": "Nome da categoria",
        "maior_lucro": "Nome da categoria",
        "maior_margem": "Nome da categoria"
    }},
    "conclusao": "Conclusão executiva baseada exclusivamente nos dados fornecidos"
}}

Não invente números ou informações.
Utilize somente os dados fornecidos.
"""

resposta_json = client.models.generate_content(
    model="models/gemini-3.5-flash",
    contents=prompt_json
)

print(resposta_json.text)

{
    "resumo": "A Lumetra registrou um faturamento total de R$ 1,835,037.86 e custos de R$ 1,000,593.00, resultando em um lucro bruto de R$ 834,444.86 com uma margem bruta de 45.47%.",
    "pontos_positivos": [
        "Atingimento de uma margem bruta de 45.47%, gerando R$ 834,444.86 em lucro bruto.",
        "Destaque para a loja Asa Sul e para a categoria Eletrônicos, que lideram tanto em faturamento quanto em lucro.",
        "Pico de faturamento mensal registrado em 2026-01, alcançando R$ 168,067.95."
    ],
    "pontos_atencao": [
        "Retração no faturamento mensal em 2026-02, que registrou o menor resultado com R$ 123,584.37.",
        "Custo total elevado de R$ 1,000,593.00, consumindo a maior parte do faturamento gerado."
    ],
    "lojas": {
        "maior_faturamento": "Asa Sul",
        "maior_lucro": "Asa Sul",
        "maior_margem": "Guará"
    },
    "categorias": {
        "maior_faturamento": "Eletrônicos",
        "maior_lucro": "Eletrônicos",
        "maior_margem": "Acessórios"
    },
    "conclusao": "A Lumetra demonstra uma operação com margem bruta saudável de 45.47%, ancorada pela performance da loja Asa Sul e da categoria de Eletrônicos. Contudo, há uma oscilação faturamento entre janeiro e fevereiro de 2026 e um custo total que ultrapassa R$ 1 milhão, pontos que demandam monitoramento para otimização dos resultados futuros."
}